### ISSUE TITLE
Make readme file case insensitive

### ISSUE THREAD

**Issue by OfficialCRUGG** [pxseu/anilist-readme#2]
Suggestion:
Make the readme file name case insensitive, so that combinations like `readme.md`, `README.MD`, `ReadMe.md` etc. would work and not just `README.md`

**Comment by pxseu** [comment]
Sounds like a great feature,
Thank you!

**Comment by pxseu** [comment]
Fixed in [v1.3.0](https://github.com/pxseu/anilist-readme/releases/tag/v1.3.0)
Dont mind that it took.... well how long it did
